name: TRACE
dependencies:
  - python=3.11.13
  - pip=25.2
  - numpy=2.3.1
  - scipy=1.16.0
  - scikit-learn=1.7.1
  - pandas=2.2.3
  - matplotlib=3.10.7
  - seaborn=0.13.2
  - lightgbm=4.6.0
  - pyyaml=6.0.2
  - h5py=3.14.0
  - tqdm=4.67.1
  - packaging=25.0
  - pysam=0.23.3
  - numba=0.62.1
  - llvmlite=0.45.1
  - joblib=1.5.2
  - threadpoolctl=3.5.0
  - pip:
      - einops==0.8.1
      - flash-attn==2.8.0.post2
      - loralib==0.1.2
      - ninja==1.13.0
      - plotnine==0.15.2
      - pyahocorasick==2.2.0
      - torch==2.6.0
