"""Plots for environmental-gene attribution analyses."""

import os

import pandas as pd


def _as_pdf_path(path):
    """Return an output path with a PDF suffix."""
    return f"{os.path.splitext(str(path))[0]}.pdf"

def plot_gene_attribution(attr_df, out_path="gene_attribution.pdf", top_n=30):
    """
    Plots a heatmap of the top contributing environmental genes across different model layers.
    Args:
        attr_df: DataFrame generated by compute_adaLN_gene_attribution.
        top_n: Number of globally top contributing genes to display.
    """
    from plotnine import (ggplot, aes, geom_tile, scale_fill_cmap, labs, 
                          theme_classic, theme, element_text, element_blank)
    # Select the globally strongest genes.
    gene_totals = attr_df.groupby('gene')['score'].sum().reset_index()
    top_genes = gene_totals.nlargest(top_n, 'score')['gene'].tolist()

    # Retain only genes selected for display.
    df_plot = attr_df[attr_df['gene'].isin(top_genes)].copy()

    # Order genes by their total attribution score.
    df_plot['gene'] = pd.Categorical(df_plot['gene'], categories=top_genes[::-1])
    
    # Order modules by network depth.
    layer_order = []
    for l in sorted(attr_df['layer'].unique()):
        layer_order.extend([f"L{l}-attn", f"L{l}-ffn"])
    # Retain only modules present in the result table.
    layer_order = [l for l in layer_order if l in attr_df['layer_module'].unique()]
    df_plot['layer_module'] = pd.Categorical(df_plot['layer_module'], categories=layer_order)

    p = (
        ggplot(df_plot, aes(x='layer_module', y='gene', fill='score_norm'))
        + geom_tile(color='white', size=0.2)
        + scale_fill_cmap(cmap_name='YlOrRd') 
        + labs(
            x='Model Layer & Module (AdaLN)', 
            y='Environmental Gene (Cell Context)', 
            fill='Normalized\nAttribution'
        )
        + theme_classic()
        + theme(
            axis_text_x=element_text(rotation=45, hjust=1),
            axis_text_y=element_text(size=10),
            figure_size=(max(8, len(layer_order)*0.4), max(5, top_n*0.25))
        )
    )
    pdf_path = _as_pdf_path(out_path)
    p.save(pdf_path)
    print(f"Gene attribution heatmap saved to {pdf_path}")
    return pdf_path
