d_seq: 4
d_model: 256
d_expr: 16840
d_species: 128
d_cell_env: 64
all_species: ["human", "macaque", "mouse"]
expr_dict_path: None
n_heads: 16
number_of_layers: 6
d_ff: 768
adaptive_dim: 16
p_drop: 0.1
model_name: "base_model_256d_16h_6l_64env_16ad"
