#!/usr/bin/env python3
import pandas as pd
import numpy as np
import argparse
import sys
import os

def safe_clean_id(tid):
    """
    Safely clean Transcript IDs:
    - Strip version numbers (decimals) ONLY for Ensembl IDs (e.g., ENST00001.2 -> ENST00001).
    - Keep novel IDs (MSTRG, PB, etc.) intact.
    """
    tid_str = str(tid).strip()
    if tid_str.startswith('ENS'):
        return tid_str.split('.')[0]
    return tid_str

def clean_gtex_junction_id(jid):
    """
    Remove the strand info from GTEx STAR Junction IDs to match featureCounts format.
    GTEx format: chr1:11212-12009:+  =>  featureCounts format: chr1:11212-12009
    """
    jid_str = str(jid).strip()
    if jid_str.count(':') >= 2:
        return jid_str.rsplit(':', 1)[0]
    return jid_str

def main():
    parser = argparse.ArgumentParser(description="Dual-Track GTEx Baseline Filtering (Absolute TPM & Junction Mean CPM).")
    parser.add_argument("-i", "--input", required=True, help="Input CSV: from find_tumor_specific_transcripts.py")
    parser.add_argument("--gtex_tpm", required=True, help="GTEx baseline median TPM CSV")
    parser.add_argument("--gtex_junc", required=True, help="GTEx baseline median Junction CPM CSV")
    parser.add_argument("-o", "--output", required=True, help="Output CSV: safe_tumor_specific_transcripts_GTEx-step1.csv")
    
    # Pre-computed specific junction dictionary from topological gtf analysis
    parser.add_argument("--junc_mapping", type=str, default=None, help="Path to TSV dictionary generated by extract_specific_junctions.py")
    
    # Thresholds
    parser.add_argument("--max_tpm", type=float, default=0.5, help="Track A: Max allowed median TPM in normal tissues (default: 0.5)")
    parser.add_argument("--max_jcpm", type=float, default=0.1, help="Track B: Max allowed median Junction CPM in normal tissues (default: 0.1)")
    parser.add_argument("--veto_tpm", type=float, default=2.0, help="Veto threshold: Kill Track B if GTEx TPM exceeds this value (default: 2.0)")
    
    # CTA Exemption
    parser.add_argument("--include_testis", action="store_true", help="Strict mode: Do not exclude Testis (disables CTA exemption).")
    
    args = parser.parse_args()

    # ==============================================================================
    # 1. Load Datasets
    # ==============================================================================
    print("--- Step 1: Loading Datasets ---")
    try:
        candidates = pd.read_csv(args.input)
        gtex_tpm = pd.read_csv(args.gtex_tpm)
        gtex_junc = pd.read_csv(args.gtex_junc)
    except Exception as e:
        print(f"Error loading files: {e}")
        sys.exit(1)

    print(f" -> Loaded Candidates: {len(candidates)}")
    print(f" -> Loaded GTEx TPM Matrix: {gtex_tpm.shape[0]} transcripts")
    print(f" -> Loaded GTEx Junction CPM Matrix: {gtex_junc.shape[0]} junctions")

    # ==============================================================================
    # 2. Configure CTA (Cancer-Testis Antigen) Exemption & Calculate Max Background
    # ==============================================================================
    tpm_tissues = [c for c in gtex_tpm.columns if c not in ['Transcript_ID']]
    
    # [FIXED]: Explicitly filter out Associated_Gene column found in user's real file structure
    junc_tissues = [c for c in gtex_junc.columns if c not in ['Junction_ID', 'Associated_Gene']]

    if not args.include_testis:
        tpm_tissues_check = [c for c in tpm_tissues if 'Testis' not in c]
        junc_tissues_check = [c for c in junc_tissues if 'Testis' not in c]
        print(f"\n[Notice] CTA Exemption ENABLED: Testis is excluded from normal background screening.")
    else:
        tpm_tissues_check = tpm_tissues
        junc_tissues_check = junc_tissues
        print(f"\n[Notice] Strict Mode ENABLED: Screening across ALL tissues, including Testis.")

    # Calculate Max values across all checked normal tissues
    gtex_tpm['Max_GTEx_TPM'] = gtex_tpm[tpm_tissues_check].max(axis=1).fillna(0)
    gtex_junc['Max_GTEx_JCPM'] = gtex_junc[junc_tissues_check].max(axis=1).fillna(0)

    # Clean IDs to ensure perfect matching across different pipeline components
    gtex_tpm['Join_ID_TPM'] = gtex_tpm['Transcript_ID'].apply(safe_clean_id)
    gtex_junc['Join_ID_Junc'] = gtex_junc['Junction_ID'].apply(clean_gtex_junction_id)

    # Convert GTEx lookups to dictionaries for blazing fast O(1) vectorized lookup
    dict_tpm = dict(zip(gtex_tpm['Join_ID_TPM'], gtex_tpm['Max_GTEx_TPM']))
    dict_junc = dict(zip(gtex_junc['Join_ID_Junc'], gtex_junc['Max_GTEx_JCPM']))

    # ==============================================================================
    # 3. Dual-Track Global Validation (Optimized with Specific Junction Mapping)
    # ==============================================================================
    print("\n--- Step 2: Executing Dual-Track Global Screening ---")
    
    candidates['Clean_TID'] = candidates['Transcript_ID'].apply(safe_clean_id)

    # Build inverse index mapping: Transcript_ID -> Set of specific junctions
    tx_to_spec_junc = {}
    if args.junc_mapping and os.path.exists(args.junc_mapping):
        print(f" -> Loading specific junction mapping from: {args.junc_mapping}")
        try:
            mapping_df = pd.read_csv(args.junc_mapping, sep='\t')
            for _, row in mapping_df.iterrows():
                j_id = row['Junction_ID']
                t_ids = str(row['Transcript_ID']).split(',')
                for t in t_ids:
                    t_clean = safe_clean_id(t)
                    tx_to_spec_junc.setdefault(t_clean, set()).add(j_id)
            print(f" -> Built reverse mapping index for {len(tx_to_spec_junc)} unique transcripts.")
        except Exception as e:
            print(f"[Warning] Failed to load junction mapping: {e}")

    # [CRITICAL FIXED]: Fail-safe Adaptive Multi-Junction Parsing Logic to prevent leakages
    def get_max_specific_junc_noise(row):
        t_id = row['Clean_TID']
        junc_str = row.get('Valid_Junction_IDs', '')
        
        junc_list = []
        # Priority 1: Check strictly specific junctions derived from GTF topological index
        if args.junc_mapping and t_id in tx_to_spec_junc:
            junc_list = list(tx_to_spec_junc[t_id])
            
        # Priority 2: Fallback to the run-time validated junctions if mapping row doesn't exist
        # This prevents transcripts from accidentally getting 0.0 background if they aren't indexed
        if not junc_list:
            if pd.notna(junc_str) and str(junc_str).strip() not in ['None', '', 'nan', 'NaN']:
                junc_list = [j.strip() for j in str(junc_str).split('|') if j.strip()]
                
        # Return maximum GTEx background noise among the chosen junctions
        return max([dict_junc.get(j, 0.0) for j in junc_list]) if junc_list else 0.0

    if 'Valid_Junction_IDs' not in candidates.columns:
        print("[Error] Required column 'Valid_Junction_IDs' not found in candidates table.")
        sys.exit(1)

    # Cross-reference candidate rows against normal database dictionaries
    candidates['Global_Max_GTEx_TPM'] = candidates['Clean_TID'].map(dict_tpm).fillna(0.0)
    candidates['Global_Max_GTEx_JCPM'] = candidates.apply(get_max_specific_junc_noise, axis=1)

    # --- Track A Validation ---
    # Transcript must pass local differential tracking AND be silent globally in GTEx TPM
    valid_A = candidates['Pass_TrackA_TPM'] & (candidates['Global_Max_GTEx_TPM'] < args.max_tpm)

    # --- Track B Validation ---
    # Junctions must be globally silent AND (Veto) the whole gene expression cannot exceed veto_tpm
    valid_B = candidates['Pass_TrackB_Junction'] & \
              (candidates['Global_Max_GTEx_JCPM'] <= args.max_jcpm) & \
              (candidates['Global_Max_GTEx_TPM'] < args.veto_tpm)

    # Apply global screening overwrites
    candidates['Pass_TrackA_TPM'] = valid_A
    candidates['Pass_TrackB_Junction'] = valid_B

    # ==============================================================================
    # 4. Final Consolidation & Export
    # ==============================================================================
    print("\n--- Step 3: Consolidation ---")
    # Candidates survive if they pass AT LEAST one track after global verification
    safe_candidates = candidates[candidates['Pass_TrackA_TPM'] | candidates['Pass_TrackB_Junction']].copy()
    
    if 'Shared_Patient_Count' in safe_candidates.columns:
        safe_candidates.sort_values(
            by=['Shared_Patient_Count', 'Tumor_Junction_CPM', 'Tumor_TPM'], 
            ascending=[False, False, False], 
            inplace=True
        )
    else:
        safe_candidates.sort_values(
            by=['Tumor_Junction_CPM', 'Tumor_TPM'], 
            ascending=[False, False], 
            inplace=True
        )

    print(f" -> Initial Local Candidates: {len(candidates)}")
    print(f" -> Vetoed/Excluded by GTEx Background: {len(candidates) - len(safe_candidates)}")
    print(f" -> Ultra-safe Candidates Survived: {len(safe_candidates)}")
    
    only_a = len(safe_candidates[safe_candidates['Pass_TrackA_TPM'] & ~safe_candidates['Pass_TrackB_Junction']])
    only_b = len(safe_candidates[~safe_candidates['Pass_TrackA_TPM'] & safe_candidates['Pass_TrackB_Junction']])
    both_ab = len(safe_candidates[safe_candidates['Pass_TrackA_TPM'] & safe_candidates['Pass_TrackB_Junction']])
    
    print("\nSurvival Breakdown:")
    print(f" - Survived via Track A (TPM) only: {only_a}")
    print(f" - Survived via Track B (Junc CPM) only: {only_b}")
    print(f" - Survived via Both Tracks: {both_ab} 🏆")

    # Clean up temporary mapping columns before saving
    cols_to_drop = ['Clean_TID']
    safe_candidates.drop(columns=[c for c in cols_to_drop if c in safe_candidates.columns], inplace=True)

    safe_candidates.to_csv(args.output, index=False)
    print(f"\n✅ Step 1 Dual-Track output saved to: {args.output}")

    if not safe_candidates.empty:
        print("\nPreview of Top Safe Candidates:")
        preview_cols = ['Transcript_ID']
        if 'Class_Code' in safe_candidates.columns: preview_cols.append('Class_Code')
        preview_cols.extend(['Pass_TrackA_TPM', 'Global_Max_GTEx_TPM', 'Pass_TrackB_Junction', 'Global_Max_GTEx_JCPM'])
        print(safe_candidates.drop_duplicates(subset=['Transcript_ID']).head(10)[preview_cols].to_string(index=False))

if __name__ == "__main__":
    main()