#!/usr/bin/env python3
import pandas as pd
import numpy as np
import os
import argparse
import sys

def clean_colname(col):
    """
    Clean column names robustly to extract pure Run IDs.
    """
    if '.bam' in col:
        basename = os.path.basename(col)
        return basename.replace('.uniq.sorted.bam', '').replace('.bam', '')
    return col

def calculate_tpm(counts, lengths, lib_sizes):
    """
    Calculate Absolute TPM (Transcripts Per Million) anchored to the TRUE library depth.
    """
    lengths_kb = lengths / 1000.0
    rpk = counts.div(lengths_kb, axis=0)
    matched_lib_sizes = lib_sizes[counts.columns]
    scale_factors = matched_lib_sizes / 1e6
    tpm = rpk.div(scale_factors, axis=1)
    return tpm

def classify_tissue(val):
    val_lower = str(val).lower()
    if any(kw in val_lower for kw in ['normal', 'adjacent', 'benign']):
        return 'normal'
    elif any(kw in val_lower for kw in ['tumor', 'malignant']):
        return 'tumor'
    else:
        return 'unknown'

def main():
    parser = argparse.ArgumentParser(description="Identify tumor-specific upregulated transcripts using Dual-Track (Absolute TPM & Junction Mean CPM).")
    
    parser.add_argument("-c", "--counts_file", required=True, help="RAW transcript counts file from featureCounts.")
    parser.add_argument("-s", "--summary_file", required=True, help="Path to transcript_counts.txt.summary from featureCounts.")
    parser.add_argument("-m", "--metadata_file", required=True, help="Metadata CSV file (e.g., SraRunTable.csv).")
    parser.add_argument("-o", "--output_file", required=True, help="Output CSV file for safe candidate transcripts.")
    parser.add_argument("--out_tpm_file", required=True, help="Path to save the calculated whole-transcriptome TPM matrix.")
    
    parser.add_argument("--class_mapping", type=str, default=None, help="Path to transcript_class_mapping.tsv generated by gffcompare.")
    
    parser.add_argument("--jcounts_file", type=str, default=None, help="Path to the RAW .jcounts file from featureCounts -J.")
    parser.add_argument("--junc_mapping", type=str, default=None, help="Path to the TSV dictionary generated by extract_specific_junctions.py.")
    
    parser.add_argument("--min_max_tcount", type=int, default=20, help="Track A Noise Filter.")
    parser.add_argument("--min_max_jcount", type=int, default=5, help="Track B Noise Filter.")
    
    parser.add_argument("--pseudo_count", type=float, default=0.1, help="Pseudo-count.")
    parser.add_argument("--min_tumor_tpm", type=float, default=1.0, help="Track A: Min Tumor TPM.")
    parser.add_argument("--strict_normal_max", type=float, default=0.5, help="Track A: Max Normal TPM.")
    
    parser.add_argument("--min_tumor_cpm", type=float, default=1.0, help="Track B: Min Tumor CPM.")
    parser.add_argument("--strict_normal_max_cpm", type=float, default=0.1, help="Track B: Max Normal CPM.")
    parser.add_argument("--veto_normal_tpm", type=float, default=2.0, help="Veto Track B if Normal TPM is too high.")
    
    parser.add_argument("--min_log2fc", type=float, default=2.0, help="Minimum log2 Fold Change.")
    
    args = parser.parse_args()

    # ==============================================================================
    # True Library Depth Extraction
    # ==============================================================================
    print("\n--- Step 1: Extracting Absolute Library Sizes from Summary ---")
    try:
        summary_df = pd.read_csv(args.summary_file, sep='\t', index_col=0)
        summary_df.rename(columns=clean_colname, inplace=True)
        if 'Assigned' not in summary_df.index or 'Unassigned_Ambiguity' not in summary_df.index:
            print("Error: 'Assigned' and/or 'Unassigned_Ambiguity' rows not found in the summary file.")
            sys.exit(1)
        lib_sizes = summary_df.loc['Assigned'] + summary_df.loc['Unassigned_Ambiguity']
        print(f" -> Successfully computed Absolute Library Depths for {len(lib_sizes)} samples.")
    except Exception as e:
        print(f"Error reading summary file: {e}")
        sys.exit(1)

    print("\n--- Step 2: Loading and Normalizing Transcript Counts (Track A) ---")
    counts_df = pd.read_csv(args.counts_file, sep='\t', index_col=0, comment='#')
    counts_df.rename(columns=clean_colname, inplace=True)
    length_series = counts_df['Length']
    
    cols_to_drop = ['Chr', 'Start', 'End', 'Strand', 'Length']
    cols_to_drop_existing = [c for c in cols_to_drop if c in counts_df.columns]
    raw_counts = counts_df.drop(columns=cols_to_drop_existing)

    tpm_df = calculate_tpm(raw_counts, length_series, lib_sizes)
    print(f" -> Global Absolute TPM matrix generated: {tpm_df.shape[0]} transcripts.")
    
    tpm_out_dir = os.path.dirname(args.out_tpm_file)
    if tpm_out_dir and not os.path.exists(tpm_out_dir): os.makedirs(tpm_out_dir)
    tpm_df.index.name = 'Transcript_ID'
    tpm_df.to_csv(args.out_tpm_file)
    
    max_counts = raw_counts.max(axis=1)
    valid_transcripts = raw_counts.index[max_counts > args.min_max_tcount]
    tpm_df = tpm_df.loc[valid_transcripts].copy()
    print(f" -> Transcript Regions passing noise filter (> {args.min_max_tcount} raw reads): {len(tpm_df)}")
    
    print("\n--- Step 3: Loading Metadata and Standardizing Tissue Types ---")
    meta_df = pd.read_csv(args.metadata_file)
    meta_df.columns = meta_df.columns.str.strip()
    
    tissue_col = next((col for col in meta_df.columns if 'tissue' in col.lower()), None)
    if not tissue_col:
        print("Error: Could not find a tissue column in metadata.")
        sys.exit(1)
        
    meta_df['standardized_tissue'] = meta_df[tissue_col].apply(classify_tissue)
    tumor_count = (meta_df['standardized_tissue'] == 'tumor').sum()
    normal_count = (meta_df['standardized_tissue'] == 'normal').sum()
    print(f" -> Found {tumor_count} tumor samples and {normal_count} normal samples.")
    
    normal_runs = meta_df[meta_df['standardized_tissue'] == 'normal']['Run'].tolist()
    normal_runs_tpm = [r for r in normal_runs if r in tpm_df.columns]

    j_exploded = pd.DataFrame()
    jbam_cols = []

    if args.jcounts_file and args.junc_mapping:
        print("\n--- Step 4: Live Intersecting Raw Junctions with Theoretical Dictionary (Track B) ---")
        if not os.path.exists(args.jcounts_file) or not os.path.exists(args.junc_mapping):
            print("[Error] Missing .jcounts or .junc_mapping file.")
            sys.exit(1)
            
        print(f" -> Loading specific junction dictionary: {args.junc_mapping}")
        mapping_df = pd.read_csv(args.junc_mapping, sep='\t')
        junc_dict = dict(zip(mapping_df['Junction_ID'], mapping_df['Transcript_ID']))
        print(f" -> Registered {len(junc_dict)} strict topological targets.")

        peek_df = pd.read_csv(args.jcounts_file, sep='\t', nrows=0)
        orig_cols = peek_df.columns.tolist()
        renamed_cols = [clean_colname(c) for c in orig_cols]
        jbam_cols = [c for c in renamed_cols if c in meta_df['Run'].values]
        normal_runs_junc = [r for r in normal_runs if r in jbam_cols]

        dtype_dict = {'PrimaryGene': str, 'Site1_chr': str, 'Site2_chr': str}
        chunk_size = 250000
        survivor_chunks = []
        total_raw_rows = 0
        
        chunk_iter = pd.read_csv(args.jcounts_file, sep='\t', chunksize=chunk_size, dtype=dtype_dict, low_memory=False)
        
        for chunk in chunk_iter:
            total_raw_rows += len(chunk)
            chunk.columns = renamed_cols
            
            j_keys = chunk['Site1_chr'].astype(str) + ':' + chunk['Site1_location'].astype(str) + '-' + chunk['Site2_location'].astype(str)
            
            mask = j_keys.isin(junc_dict.keys())
            filtered_chunk = chunk[mask].copy()
            
            if not filtered_chunk.empty:
                jmax_chunk = filtered_chunk[jbam_cols].max(axis=1)
                valid_chunk = filtered_chunk[jmax_chunk > args.min_max_jcount].copy()
                
                if not valid_chunk.empty:
                    valid_j_keys = j_keys[mask][jmax_chunk > args.min_max_jcount]
                    valid_chunk['Transcript_ID_Raw'] = valid_j_keys.map(junc_dict)
                    valid_chunk['Junction_ID'] = valid_j_keys
                    survivor_chunks.append(valid_chunk)
                
        if survivor_chunks:
            jcounts_raw = pd.concat(survivor_chunks, ignore_index=True)
            print(f" -> Scanned {total_raw_rows} raw events. Retained {len(jcounts_raw)} validated topological junctions.")
            
            cpm_df = jcounts_raw[jbam_cols].div(lib_sizes[jbam_cols], axis=1) * 1e6
            jcounts_raw[jbam_cols] = cpm_df
            
            jcounts_raw['Transcript_ID'] = jcounts_raw['Transcript_ID_Raw'].astype(str).str.split(',')
            j_exploded = jcounts_raw.explode('Transcript_ID')
            
            if normal_runs_junc:
                j_exploded['Max_Normal_CPM_All'] = j_exploded[normal_runs_junc].max(axis=1)
            else:
                j_exploded['Max_Normal_CPM_All'] = 0.0
        else:
            print(f" -> Scanned {total_raw_rows} raw events. None passed the strict topological AND expression filters.")

    print("\n--- Step 5: Dual-Track Paired Analysis (Identifying Targets) ---")
    results_list = []

    for patient, group in meta_df.groupby('Individual'):
        t_run_arr = group[group['standardized_tissue'] == 'tumor']['Run'].values
        n_run_arr = group[group['standardized_tissue'] == 'normal']['Run'].values
        
        # [NOTICE]: Added explicit warning for skipped patients
        if len(t_run_arr) != 1 or len(n_run_arr) != 1:
            print(f" [Warning] Patient {patient} skipped: requires exactly 1 tumor and 1 normal sample (found T:{len(t_run_arr)}, N:{len(n_run_arr)}).")
            continue
            
        t_run = t_run_arr[0]
        n_run = n_run_arr[0]
        
        cands_a = set()
        t_tpm = pd.Series(dtype=float)
        n_tpm = pd.Series(dtype=float)
        
        if t_run in tpm_df.columns and n_run in tpm_df.columns:
            t_tpm = tpm_df[t_run]
            n_tpm = tpm_df[n_run]
            log2fc_tpm = np.log2((t_tpm + args.pseudo_count) / (n_tpm + args.pseudo_count))
            mask_a = (t_tpm >= args.min_tumor_tpm) & (log2fc_tpm >= args.min_log2fc)
            cands_a = set(tpm_df[mask_a].index)
        
        cands_b = set()
        j_pair = pd.DataFrame()
        if not j_exploded.empty and t_run in jbam_cols and n_run in jbam_cols:
            j_t = j_exploded[['Transcript_ID', 'Junction_ID', t_run]].rename(columns={t_run: 'T_CPM'})
            j_n = j_exploded[['Transcript_ID', 'Junction_ID', n_run]].rename(columns={n_run: 'N_CPM'})
            j_pair = pd.merge(j_t, j_n, on=['Transcript_ID', 'Junction_ID'])
            
            j_pair['Log2FC_CPM'] = np.log2((j_pair['T_CPM'] + args.pseudo_count) / (j_pair['N_CPM'] + args.pseudo_count))
            mask_b = (j_pair['T_CPM'] >= args.min_tumor_cpm) & (j_pair['Log2FC_CPM'] >= args.min_log2fc)
            cands_b = set(j_pair[mask_b]['Transcript_ID'])

        all_cands = cands_a.union(cands_b)
        
        for tx_id in all_cands:
            pass_a = tx_id in cands_a
            pass_b = tx_id in cands_b
            
            t_tpm_val = t_tpm.get(tx_id, 0.0)
            n_tpm_val = n_tpm.get(tx_id, 0.0)
            max_norm_tpm = tpm_df.loc[tx_id, normal_runs_tpm].max() if tx_id in tpm_df.index and normal_runs_tpm else 0.0
            
            valid_j_ids = "None"
            t_cpm_val, n_cpm_val, max_norm_cpm = 0.0, 0.0, 0.0
            
            if pass_b and not j_pair.empty:
                tx_juncs = j_pair[(j_pair['Transcript_ID'] == tx_id) & mask_b]
                if not tx_juncs.empty:
                    t_cpm_val = tx_juncs['T_CPM'].mean()
                    n_cpm_val = tx_juncs['N_CPM'].mean()
                    valid_j_ids = "|".join(tx_juncs['Junction_ID'].astype(str).tolist())
                    max_norm_cpm = j_exploded[j_exploded['Junction_ID'].isin(tx_juncs['Junction_ID'])]['Max_Normal_CPM_All'].max()
            
            results_list.append({
                'Transcript_ID': tx_id,
                'Patient': patient,
                'Pass_TrackA_TPM': pass_a,
                'Pass_TrackB_Junction': pass_b,
                'Tumor_Run': t_run,
                'Normal_Run': n_run,
                'Tumor_TPM': round(t_tpm_val, 3),
                'Normal_TPM': round(n_tpm_val, 3),
                'Max_Normal_TPM_All': round(max_norm_tpm, 3),
                'Valid_Junction_IDs': valid_j_ids,  
                'Tumor_Junction_CPM': round(t_cpm_val, 3),
                'Normal_Junction_CPM': round(n_cpm_val, 3),
                'Max_Normal_Junction_CPM_All': round(max_norm_cpm, 3)
            })

    results_df = pd.DataFrame(results_list)
    if results_df.empty:
        print("\nNo tumor-specific upregulated events found based on the given thresholds.")
        sys.exit(0)

    print("\n--- Step 6: Strict Global Background Filtering ---")

    valid_A = results_df['Pass_TrackA_TPM'] & (results_df['Max_Normal_TPM_All'] < args.strict_normal_max)
    
    valid_B = pd.Series(False, index=results_df.index)
    if args.jcounts_file and args.junc_mapping:
        valid_B = results_df['Pass_TrackB_Junction'] & \
                  (results_df['Max_Normal_Junction_CPM_All'] < args.strict_normal_max_cpm) & \
                  (results_df['Max_Normal_TPM_All'] < args.veto_normal_tpm)
        
    safe_candidates_df = results_df[valid_A | valid_B].copy()
    
    safe_candidates_df['Pass_TrackA_TPM'] = valid_A
    safe_candidates_df['Pass_TrackB_Junction'] = valid_B

    print(f"Remaining after strictly filtering out high normal background (Veto threshold: TPM < {args.veto_normal_tpm}): {len(safe_candidates_df)}")
    if safe_candidates_df.empty:
        print("No candidates passed the strict normal background filter. Exiting.")
        sys.exit(0)

    # ==============================================================================
    # Final Consolidation and Export (Removed Shared Patient Logic)
    # ==============================================================================
    final_targets = safe_candidates_df.copy()

    if args.class_mapping and os.path.exists(args.class_mapping):
        class_df = pd.read_csv(args.class_mapping, sep='\t')
        if 'Transcript_ID' in class_df.columns:
            final_targets = pd.merge(final_targets, class_df, on='Transcript_ID', how='left')
            final_targets['Class_Code'] = final_targets['Class_Code'].fillna('Unknown')
            final_targets['Ref_Gene_Name'] = final_targets['Ref_Gene_Name'].fillna('Unknown')

    # Re-oriented sorting strictly by Expression signals
    final_targets = final_targets.sort_values(
        by=['Tumor_Junction_CPM', 'Tumor_TPM'], 
        ascending=[False, False]
    )

    out_dir = os.path.dirname(args.output_file)
    if out_dir and not os.path.exists(out_dir): os.makedirs(out_dir)

    cols = ['Transcript_ID']
    if 'Class_Code' in final_targets.columns: cols.extend(['Class_Code', 'Ref_Gene_Name'])
    
    # Removed coverage columns
    cols.extend(['Patient', 'Tumor_Run', 'Normal_Run', 
                 'Pass_TrackA_TPM', 'Tumor_TPM', 'Normal_TPM', 'Max_Normal_TPM_All', 
                 'Pass_TrackB_Junction', 'Valid_Junction_IDs', 'Tumor_Junction_CPM', 'Normal_Junction_CPM', 'Max_Normal_Junction_CPM_All'])
    
    final_targets = final_targets[cols]

    final_targets.to_csv(args.output_file, index=False)
    print(f"Successfully saved all safe candidate transcripts to: {args.output_file}")
    
    print("\nPreview of Top Candidates:")
    preview_cols = ['Transcript_ID']
    if 'Class_Code' in final_targets.columns: preview_cols.append('Class_Code')
    preview_cols.extend(['Pass_TrackA_TPM', 'Pass_TrackB_Junction', 'Tumor_Junction_CPM', 'Tumor_TPM'])
    
    preview_df = final_targets.drop_duplicates(subset=['Transcript_ID']).head(10)
    print(preview_df[preview_cols].to_string(index=False))

if __name__ == "__main__":
    main()